"""
Agents Generator

Generates agent implementations from goal spec.
Each agent gets its own module with:
- Agent class inheriting from BaseAgent
- LangGraph node function
- Agent-specific logic based on kind (supervisor/llm_agent/function_agent)
"""

import os
from pathlib import Path
from typing import Dict, Any
from template_engine import TemplateEngine


def generate(spec: Dict[str, Any], out_dir: str, dry_run: bool = False):
    """
    Generate agent implementations

    Creates:
    - langgraph/agents/<agent_name>.py for each agent in spec
    - langgraph/agents/__init__.py with all agent imports
    """

    print("[agents] Generating agent implementations...")

    # Setup paths
    out_path = Path(out_dir)
    agents_dir = out_path / "langgraph" / "agents"

    if not dry_run:
        agents_dir.mkdir(parents=True, exist_ok=True)

    # Setup template engine
    templates_dir = Path(__file__).parent.parent / "templates"
    engine = TemplateEngine(templates_dir)

    # Get agents from spec
    agents = spec.get("agents", {})

    if not agents:
        print("[agents] Warning: No agents defined in spec")
        return

    # Get additional context for templates
    goal_id = spec.get("id", "unknown")
    context_fields = spec.get("state_management", {}).get("state", {}).get("schema", {}).get("context_fields", [])
    topology = spec.get("topology", {})

    generated_agents = []

    # Generate each agent
    for agent_name, agent_config in agents.items():
        print(f"[agents]   Generating {agent_name} ({agent_config.get('kind', 'unknown')})...")

        # Prepare context for template
        context = {
            "goal_id": goal_id,
            "agent_name": agent_name,
            "agent": agent_config,
            "context_fields": context_fields,
            "topology": topology,
        }

        # Render agent implementation
        output_file = agents_dir / f"{agent_name}.py"

        if dry_run:
            print(f"[agents]     Would write: {output_file}")
        else:
            engine.render_to_file(
                "agents/agent_impl.py.j2",
                context,
                output_file
            )
            print(f"[agents]     ✓ {output_file}")

        generated_agents.append(agent_name)

    # Generate __init__.py to export all agents
    init_content = _generate_init_file(generated_agents)
    init_file = agents_dir / "__init__.py"

    if dry_run:
        print(f"[agents]   Would write: {init_file}")
    else:
        init_file.write_text(init_content)
        print(f"[agents]   ✓ {init_file}")

    print(f"[agents] ✓ Generated {len(generated_agents)} agents")


def _generate_init_file(agent_names: list) -> str:
    """Generate __init__.py for agents module"""

    lines = [
        '"""',
        'Agent implementations',
        '',
        'Auto-generated by GoalGen',
        '"""',
        '',
    ]

    # Import statements
    for agent_name in agent_names:
        class_name = _to_pascal_case(agent_name)
        lines.append(f"from .{agent_name} import {class_name}, {agent_name}_node")

    lines.append("")
    lines.append("__all__ = [")

    # Export list
    for agent_name in agent_names:
        class_name = _to_pascal_case(agent_name)
        lines.append(f'    "{class_name}",')
        lines.append(f'    "{agent_name}_node",')

    lines.append("]")
    lines.append("")

    return "\n".join(lines)


def _to_pascal_case(snake_str: str) -> str:
    """Convert snake_case to PascalCase"""
    return "".join(word.capitalize() for word in snake_str.split("_"))
