"""
LangGraph Generator

Generates LangGraph workflow orchestration from goal spec.

Creates:
- quest_builder.py - Main graph construction with StateManager
- state_schema.py - TypedDict state definition from context_fields
- checkpointer_adapter.py - Backend-specific checkpointer
"""

import os
from pathlib import Path
from typing import Dict, Any
from template_engine import TemplateEngine


def generate(spec: Dict[str, Any], out_dir: str, dry_run: bool = False):
    """
    Generate LangGraph workflow

    Creates:
    - langgraph/quest_builder.py
    - langgraph/state_schema.py
    - langgraph/checkpointer_adapter.py
    - langgraph/__init__.py
    """

    print("[langgraph] Generating LangGraph workflow...")

    # Setup paths
    out_path = Path(out_dir)
    langgraph_dir = out_path / "langgraph"
    agents_dir = langgraph_dir / "agents"
    evaluators_dir = langgraph_dir / "evaluators"

    if not dry_run:
        langgraph_dir.mkdir(parents=True, exist_ok=True)
        agents_dir.mkdir(parents=True, exist_ok=True)
        evaluators_dir.mkdir(parents=True, exist_ok=True)

        # Create __init__.py files for subdirectories
        (agents_dir / "__init__.py").write_text('"""Agent implementations"""\n')
        (evaluators_dir / "__init__.py").write_text('"""Evaluator implementations"""\n')

    # Setup template engine
    templates_dir = Path(__file__).parent.parent / "templates"
    engine = TemplateEngine(templates_dir)

    # Extract context from spec
    context = _build_context(spec)

    # Generate files
    files = [
        ("langgraph/quest_builder.py.j2", "quest_builder.py"),
        ("langgraph/state_schema.py.j2", "state_schema.py"),
        ("langgraph/checkpointer_adapter.py.j2", "checkpointer_adapter.py"),
    ]

    # Add schema_migrations.py if schema_migrations defined in spec
    if context.get("schema_migrations"):
        files.append(("langgraph/schema_migrations.py.j2", "schema_migrations.py"))

    for template_name, output_filename in files:
        output_path = langgraph_dir / output_filename

        if dry_run:
            print(f"[langgraph]   Would write: {output_path}")
        else:
            engine.render_to_file(template_name, context, output_path)
            print(f"[langgraph]   ✓ {output_path}")

    # Generate __init__.py
    init_content = _generate_init_file()
    init_file = langgraph_dir / "__init__.py"

    if dry_run:
        print(f"[langgraph]   Would write: {init_file}")
    else:
        init_file.write_text(init_content)
        print(f"[langgraph]   ✓ {init_file}")

    print("[langgraph] ✓ LangGraph workflow generated")


def _build_context(spec: Dict[str, Any]) -> Dict[str, Any]:
    """Build template context from spec"""

    goal_id = spec.get("id", "unknown")
    agents = spec.get("agents", {})
    evaluators = spec.get("evaluators", {})
    tasks = spec.get("tasks", [])
    topology = spec.get("topology", {})

    # State management config
    state_config = spec.get("state_management", {}).get("state", {}).get("schema", {})
    context_fields_raw = state_config.get("context_fields", [])
    context_descriptions = state_config.get("descriptions", {})

    # Convert context_fields to dict format if it's a list
    if isinstance(context_fields_raw, list):
        context_fields = {
            field: {
                "type": "str",  # Default type
                "description": context_descriptions.get(field, "")
            }
            for field in context_fields_raw
        }
    else:
        context_fields = context_fields_raw

    # Schema versioning
    schema_version = spec.get("schema_version", 1)
    schema_migrations = spec.get("schema_migrations", {})

    # Checkpointing backend
    checkpointing_config = spec.get("state_management", {}).get("checkpointing", {})
    checkpointing_backend = checkpointing_config.get("backend", "memory")

    return {
        "goal_id": goal_id,
        "agents": agents,
        "evaluators": evaluators,
        "tasks": tasks,
        "topology": topology,
        "context_fields": context_fields,
        "context_descriptions": context_descriptions,
        "schema_version": schema_version,
        "schema_migrations": schema_migrations,
        "checkpointing_backend": checkpointing_backend,
    }


def _generate_init_file() -> str:
    """Generate __init__.py for langgraph module"""

    return '''"""
LangGraph Workflow

Auto-generated by GoalGen
"""

from .quest_builder import graph

__all__ = ["graph"]
'''
